baseURL = 'https://mocpy.cz/'
languageCode = 'en-us'
title = 'Mocpy'
theme = "notrack"
pagination.pagerSize = 4  # Posts per page, e.g. in the blog

[params]
author = "Mocpy"
siteHeading = "Mocpy" # defaults to author
# favicon = "hugo_grotius.png" # The small icon shown in browser tabs
showTaxonomyLinks = false  # Show e.g. a "Category" button at top of blog page
footer = """This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>"""

# You can choose to display a summary of your blog on the home page. Below are
# the settings relevant for that.
showBlogLatest = true  # Whether to show it or not
mainSections = ["blog"]  # Section name of your blog (folder name)
blogLatestHeading = "My writing"  # Heading above blog summary
nBlogLatest = 4  # Number of blog post in summary

[params.social]
github = "Mocpy"
email = "mocpy@seznam.cz"
rss = "yes"  # Value doesn't matter - it will always link to your blog RSS

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
